name: Fork Notification
on: fork

jobs:
  create-fork-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create fork notification issue
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New Repository Fork Created',
              body: `A new fork of this repository has been created by @${{ github.actor }}\n\n@PhasesResearchLab/ultera-maintainers`
            });